[groups.Fixed]
name = "Fixed"
publish = true
cc-types = ["fix"]

[groups."Continuous Integration"]
name = "Continuous Integration"
publish = false
cc-types = ["ci"]

[groups.Deprecated]
name = "Deprecated"
publish = false
cc-types = ["deprecated"]

[groups.Changed]
name = "Changed"
publish = true
cc-types = ["refactor"]

[groups.Build]
name = "Build"
publish = false
cc-types = ["build"]

[groups.Chore]
name = "Chore"
publish = false
cc-types = ["chore"]

[groups.Testing]
name = "Testing"
publish = false
cc-types = ["test"]

[groups.Added]
name = "Added"
publish = true
cc-types = ["feat"]

[groups.Removed]
name = "Removed"
publish = false
cc-types = ["removed"]

[groups.Documentation]
name = "Documentation"
publish = false
cc-types = [
    "doc",
    "docs",
]

[groups.Miscellaneous]
name = "Miscellaneous"
publish = false
cc-types = ["misc"]

[groups.Security]
name = "Security"
publish = false
cc-types = [
    "security",
    "dependency",
]

[groups-mapping]
build = "Build"
chore = "Chore"
ci = "Continuous Integration"
dependency = "Security"
deprecated = "Deprecated"
doc = "Documentation"
docs = "Documentation"
feat = "Added"
fix = "Fixed"
misc = "Miscellaneous"
refactor = "Changed"
removed = "Removed"
security = "Security"
test = "Testing"

[headings]
Added = 1
Changed = 3
Fixed = 2

[display-sections]
custom = 3

[release-pattern]
prefix = "v"
